version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php-ssh.dockerfile
    container_name: gimnazia_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "2224:22"
    networks:
      - gimnazia
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: gimnazia_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - gimnazia
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    container_name: gimnazia_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pbcv_vg
      MYSQL_USER: 29m~f2bXM
      MYSQL_PASSWORD: пароль_тут
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - gimnazia

  composer:
    image: composer:latest
    container_name: gimnazia_composer
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: ["tail", "-f", "/dev/null"]
    networks:
      - gimnazia

networks:
  gimnazia:
