version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: docker/php-ssh.dockerfile
    container_name: gimnazia_app
    restart: always
    volumes:
      - ./:/var/www
    networks:
      - gimnazia
    depends_on:
      - mysql
      - redis
    healthcheck:
      test: ["CMD", "php", "/var/www/artisan", "horizon:status"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    container_name: gimnazia_redis
    restart: unless-stopped
    networks:
      - gimnazia

  mysql:
    image: mysql:5.7
    container_name: gimnazia_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pbcv_vg
      MYSQL_USER: pbcv_vg
      MYSQL_PASSWORD: "!29m~f2bXM"
    networks:
      - gimnazia

  gimnazia_nginx:
    image: nginx:alpine
    container_name: gimnazia_nginx
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - gimnazia

networks:
  gimnazia:
