version: '3.8'

services:
  app:
    image: gimnazia/php-ssh:8.1
    build:
      context: .
      dockerfile: docker/php-ssh.dockerfile
    container_name: gimnazia_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    environment:
      - VIRTUAL_HOST=gimnazia.vashkivtsi.com.ua
      - LETSENCRYPT_HOST=gimnazia.vashkivtsi.com.ua
      - LETSENCRYPT_EMAIL=info@gimnazia.vashkivtsi.com.ua
#    expose:
#      - "9000"
    networks:
      - gimnazia
    depends_on:
      - mysql

  gimnazia_nginx:
    image: nginx:alpine
    container_name: gimnazia_nginx
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - gimnazia

#  letsencrypt:
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    container_name: nginx-letsencrypt
#    restart: always
#    environment:
#      - DEFAULT_EMAIL=info@gimnazia.vashkivtsi.com.ua
#    volumes_from:
#      - nginx-proxy
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - ./certs:/etc/nginx/certs:rw
#      - ./vhost.d:/etc/nginx/vhost.d
#      - ./html:/usr/share/nginx/html
#    networks:
#      - gimnazia

  mysql:
    image: mysql:5.7
    container_name: gimnazia_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pbcv_vg
      MYSQL_USER: pbcv_vg
      MYSQL_PASSWORD: "!29m~f2bXM"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - gimnazia

  composer:
    image: composer:latest
    container_name: gimnazia_composer
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: ["tail", "-f", "/dev/null"]
    networks:
      - gimnazia

networks:
  gimnazia:
